/** @deprecated Import from `@/lib/configurator-context` — re-exported for compatibility. */
export {
  ConfiguratorProvider,
  useConfigurator,
  selectAllModules,
  clampToBox,
  rectsCollide,
  sameGroup,
  GRID_MM,
  SNAP_MM,
  MIN_BOX_MM,
  MAX_BOX_MM,
  type ViewMode,
  type DragGhost,
  type CanvasDragSession,
  type ModuleEditValues,
  type ConfiguratorStore,
  type InsertLayer,
  type ConfiguratorCoreState,
} from "@/lib/configurator-context";
